// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use crate::schema::*;

use chrono::DateTime;
use chrono::offset::Utc;
use diesel::sql_types::Json;

#[derive(Queryable, Debug, Identifiable)]
pub struct Account {
    pub id: String,
    pub email: String,
    pub username: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Queryable, Debug, Identifiable)]
pub struct Message {
    pub id: String,
    pub from: String,
    pub to: String,
    pub content_type: i32,
    pub metadata: Json,
    pub text: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Queryable, Debug, Identifiable)]
#[primary_key(revision)]
pub struct Operation {
    pub revision: i64,
    pub op_type: i32,
    pub source: String,
    pub destination: Vec<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Queryable, Debug)]
pub struct Profile {
    pub id: String,
    pub display_name: String,
    pub status_message: Option<String>,
    pub icon_path: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

