[package]
name = "op"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.7.2"
prost = "0.10.4"
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = "0.1.9"
futures = "0.3.21"

[build-dependencies]
tonic-build = "0.7.2"