services:
  db:
    image: mysql:8.0-oracle
    container_name: msg-db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSOWRD: "${MYSQL_PASSWORD}"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql/db/data:/var/lib/mysql
      - ./mysql/db/conf.d:/etc/mysql/conf.d/user.cnf
      - ./mysql/db/sql:/docker-entrypoint-initdb.d
    networks:
      - internal


  pulsar:
    image: apachepulsar/pulsar:2.9.1
    container_name: msg-pulsar-dev
    ports:
      - "6650:6650"
      - "8080:8080"
    command: bin/pulsar standalone
    volumes:
      - type: volume
        source: pulsardata
        target: "/pulsar/data"
      - type: volume
        source: pulsarconf
        target: "/pulsar/conf"

  idgen:
    image: messenger-idgen
    build:
      context: .
      dockerfile: ./idgen/Dockerfile
    container_name: msg-idgen-dev
    networks:
      - internal

  blob-storage:
    image: messenger-blob-storage
    build:
      context: .
      dockerfile: ./blob/Dockerfile
    container_name: msg-blob-dev
    volumes:
      - ./blob/storage:/usr/local/app/storage
    ports:
      - "4040:4040"
    networks:
      - internal

  talk:
    image: messenger-talk
    build:
      context: .
      dockerfile: ./grpc/talk/Dockerfile
    container_name: msg-talk-dev
    ports:
      - "50050:50050"
    networks:
      - internal

networks:
  internal: {}

volumes:
  pulsardata:
  pulsarconf: