FROM lukemathwalker/cargo-chef:latest AS chef
WORKDIR app

FROM chef as planner
COPY ./grpc .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as builder
COPY --from=planner /app/recipe.json recipe.json
RUN apt-get update && apt-get -y install cmake
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN apt-get update && apt-get -y install cmake
RUN cargo build --release

FROM debian:buster-slim as runtime
WORKDIR app
COPY --from=builder /app/target/release/talk /usr/local/bin
ENTRYPOINT ["/usr/local/bin/talk"]
